name: Deploy Website
'on':
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install apache server
        run: >
           sudo apt update

           sudo apt install -y apache2

      - name: Copy HTML folder to remote server
        run: >
          sudo cp -r ./* /var/www/html
      - name: Verify HTML folder on remote server
        run: >
           cd /var/www/html
           ls -a 

         
