name: Deploy Website
'on':
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: '${{ secrets.SSH_PRIVATE_KEY }}'
      - name: Install Apache2 on remote server
        run: >
          ssh -o StrictHostKeyChecking=no -i "private (2).pem"
          root@67.205.143.235 <<EOF

          apt update

          apt install -y apache2

          EOF
      - name: Copy HTML folder to remote server
        run: >
          scp -o StrictHostKeyChecking=no -i "private (2).pem" -r *
          root@67.205.143.235:/var/www/html
      - name: Verify HTML folder on remote server
        run: >
          ssh -o StrictHostKeyChecking=no -i "private (2).pem"
          root@67.205.143.235 <<EOF

          cd /var/www/html

          ls

          EOF
